import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import data from '../data/cats.json'
import { useState } from 'react'
import Card from '../components/Card/index.js'
import Link from 'next/link'
import Navbar from '../components/Navbar'



export default function Home() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <div className={styles.options}>
          {
            information && information.map((info, index) => {
              return (
                <Card
                  key={index}
                  name={info.catName}
                  city={info.city}
                  colour="bisque"
                  font="42px"
                />
              )
            })
          }
        </div>
      </main>
    </>
  )
}
